version: '3.8'
networks:
  backend:
    name: backend
services:
  db:
    image: mysql:8.0
    container_name: debian-db-1
    cap_add:
      - SYS_NICE
    restart: always
    env_file: .env
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql-config:/etc/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --user=$MYSQL_USER --password=$MYSQL_PASSWORD
      interval: 2s
      timeout: 20s
      retries: 10
    tty: true
    networks:
      - backend
volumes:
  db:
    driver: local
